spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Chandu@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.application.name=ecommerce-Maven
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandanathanakanti@gmail.com
spring.mail.password=cmujcshucfvscmnl
razorpay.key.id=rzp_test_xxxxxxxxx
razorpay.key.secret=xxxxxxxxxxxxxxxx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true